### ISSUE TITLE
Lacking of cfg.yaml

### ISSUE THREAD

**Issue by WangZhe1026** [craigleili/AttentiveFMaps#2]
Hello,
        I'm interested in this work, it's a fantastic work and I want to run it these days.
        But it seems to be missing a cfg file. So can you provide a usable cfg file to me?
        Thank you!

**Comment by craigleili** [comment]
Hello,
Thank you for your interests in our work.
Please check out the `Data` section in [README.md](https://github.com/craigleili/AttentiveFMaps/blob/main/README.md)
